const $ = (s) => document.querySelector(s);
const input = $("#metarInput");
const results = $("#results");
const errorBox = $("#error");

const WX = {
  MI: "shallow",
  PR: "partial",
  BC: "patches",
  DR: "low drifting",
  BL: "blowing",
  SH: "showers",
  TS: "thunderstorm",
  FZ: "freezing",
  DZ: "drizzle",
  RA: "rain",
  SN: "snow",
  SG: "snow grains",
  IC: "ice crystals",
  PL: "ice pellets",
  GR: "hail",
  GS: "small hail/snow pellets",
  UP: "unknown precipitation",
  BR: "mist",
  FG: "fog",
  FU: "smoke",
  VA: "volcanic ash",
  DU: "widespread dust",
  SA: "sand",
  HZ: "haze",
  PY: "spray",
  PO: "dust/sand whirls",
  SQ: "squalls",
  FC: "funnel cloud/tornado/waterspout",
  SS: "sandstorm",
  DS: "duststorm",
};

// Station metadata is generated by scripts/update_stations.py and served as static JSON.
let STATIONS = {};
let stationDataReady = false;

async function loadStationDatabase() {
  const status = $("#stationDataStatus");
  try {
    const response = await fetch("./data/stations.json", { cache: "no-cache" });
    if (!response.ok) throw new Error(`HTTP ${response.status}`);
    const data = await response.json();
    if (!data || typeof data !== "object" || Array.isArray(data))
      throw new Error("Unexpected station database format");
    STATIONS = data;
    stationDataReady = true;
    if (status)
      status.textContent = `Station database ready (${Object.keys(STATIONS).length.toLocaleString()} stations).`;
  } catch (err) {
    console.error("Station database failed to load:", err);
    STATIONS = {};
    stationDataReady = true;
    if (status)
      status.textContent =
        "Station metadata unavailable; decoder will use UTC.";
  }
}

const stationDataPromise = loadStationDatabase();
function stationMeta(id) {
  return STATIONS[id] || null;
}
function observationDateUTC(t) {
  if (!t) return null;
  const now = new Date();
  let d = new Date(
    Date.UTC(now.getUTCFullYear(), now.getUTCMonth(), t.day, t.hour, t.minute),
  );
  const diff = d - now;
  if (diff > 15 * 86400000)
    d = new Date(
      Date.UTC(
        now.getUTCFullYear(),
        now.getUTCMonth() - 1,
        t.day,
        t.hour,
        t.minute,
      ),
    );
  else if (diff < -20 * 86400000)
    d = new Date(
      Date.UTC(
        now.getUTCFullYear(),
        now.getUTCMonth() + 1,
        t.day,
        t.hour,
        t.minute,
      ),
    );
  return d;
}
function stationLocalTime(d) {
  if (!d.time) return "Observation time unavailable";
  const date = observationDateUTC(d.time),
    meta = stationMeta(d.station),
    tz = meta?.timezone;
  if (!tz)
    return `Day ${d.time.day}, ${String(d.time.hour).padStart(2, "0")}:${String(d.time.minute).padStart(2, "0")} UTC · local time unavailable`;
  try {
    return (
      new Intl.DateTimeFormat("en-US", {
        timeZone: tz,
        month: "short",
        day: "numeric",
        hour: "numeric",
        minute: "2-digit",
        hour12: true,
        timeZoneName: "short",
      }).format(date) + " (Local Time)"
    );
    // }).format(date);
  } catch (e) {
    return `Day ${d.time.day}, ${String(d.time.hour).padStart(2, "0")}:${String(d.time.minute).padStart(2, "0")} UTC`;
  }
}
function stationDescription(d) {
  const meta = stationMeta(d.station);
  if (!meta) return "Station metadata not in local database";
  return [meta.name, [meta.city, meta.region].filter(Boolean).join(", ")]
    .filter(Boolean)
    .join(" · ");
}

const CLOUD = {
  FEW: "Few",
  SCT: "Scattered",
  BKN: "Broken",
  OVC: "Overcast",
  VV: "Vertical visibility",
  SKC: "Sky clear",
  CLR: "Clear below 12,000 ft",
  NSC: "No significant cloud",
  NCD: "No cloud detected",
};

function updateClock() {
  $("#utcClock").textContent = new Date().toISOString().slice(11, 19) + "Z";
}
setInterval(updateClock, 1000);
updateClock();

function tempValue(s) {
  if (!s || s === "//") return null;
  return Number(s.replace("M", "-"));
}
function cToF(c) {
  return Math.round((c * 9) / 5 + 32);
}
function compass(deg) {
  const p = [
    "N",
    "NNE",
    "NE",
    "ENE",
    "E",
    "ESE",
    "SE",
    "SSE",
    "S",
    "SSW",
    "SW",
    "WSW",
    "W",
    "WNW",
    "NW",
    "NNW",
  ];
  return p[Math.round(deg / 22.5) % 16];
}

function parseVisibility(tokens, i) {
  if (tokens[i] === "CAVOK")
    return {
      used: 1,
      data: {
        code: "CAVOK",
        miles: null,
        display: "10 km or more",
        sub: "No significant weather/cloud below CAVOK limits",
        cavok: true,
      },
    };
  let code = tokens[i],
    m = code.match(/^(M|P)?(\d+)?(?:\s)?(\d\/\d)?SM$/);
  if (m) {
    let val = 0;
    if (m[2]) val += Number(m[2]);
    if (m[3]) {
      let [a, b] = m[3].split("/").map(Number);
      val += a / b;
    }
    return {
      used: 1,
      data: {
        code,
        miles: val,
        display: `${m[1] === "M" ? "< " : m[1] === "P" ? "> " : ""}${val} statute mile${val === 1 ? "" : "s"}`,
      },
    };
  }
  if (/^\d+$/.test(code) && tokens[i + 1] && /^\d\/\dSM$/.test(tokens[i + 1])) {
    let [a, b] = tokens[i + 1].replace("SM", "").split("/").map(Number),
      val = Number(code) + a / b;
    return {
      used: 2,
      data: {
        code: `${code} ${tokens[i + 1]}`,
        miles: val,
        display: `${val} statute miles`,
      },
    };
  }
  if (/^\d{4}$/.test(code)) {
    return {
      used: 1,
      data: {
        code,
        miles: null,
        display: `${Number(code) / 1000} km`,
        meters: Number(code),
      },
    };
  }
  return null;
}

function decodeWeather(code) {
  let original = code,
    intensity = "";
  if (code[0] === "-") {
    intensity = "Light ";
    code = code.slice(1);
  } else if (code[0] === "+") {
    intensity = "Heavy ";
    code = code.slice(1);
  } else if (code.startsWith("VC")) {
    intensity = "In the vicinity: ";
    code = code.slice(2);
  }
  const parts = [];
  for (let i = 0; i < code.length; ) {
    const pair = code.slice(i, i + 2);
    if (WX[pair]) {
      parts.push(WX[pair]);
      i += 2;
    } else {
      i++;
    }
  }
  return {
    code: original,
    description:
      intensity +
      (parts.length ? parts.join(" ") : "Unrecognized weather group"),
  };
}

function parse(raw) {
  const clean = raw.trim().toUpperCase().replace(/\s+/g, " ");
  if (!clean) throw new Error("Enter a METAR to decode.");
  const tokens = clean.split(" ");
  const out = {
    raw: clean,
    type: "METAR",
    station: null,
    time: null,
    wind: null,
    variableWind: null,
    visibility: null,
    weather: [],
    clouds: [],
    temp: null,
    dew: null,
    preciseTemp: null,
    preciseDew: null,
    altimeter: null,
    remarks: null,
    decodedRemarks: [],
  };
  let i = 0;
  if (["METAR", "SPECI"].includes(tokens[i])) out.type = tokens[i++];
  if (/^[A-Z0-9]{4}$/.test(tokens[i] || "")) out.station = tokens[i++];
  else
    throw new Error(
      "I could not identify a four-character station identifier at the start of this report.",
    );
  for (; i < tokens.length; i++) {
    let t = tokens[i];
    if (t === "RMK") {
      out.remarks = tokens.slice(i + 1).join(" ");
      parseRemarks(out);
      break;
    }
    if (/^(AUTO|COR|NIL)$/.test(t)) continue;
    let m;
    if ((m = t.match(/^(\d{2})(\d{2})(\d{2})Z$/))) {
      out.time = { code: t, day: +m[1], hour: +m[2], minute: +m[3] };
      continue;
    }
    if ((m = t.match(/^(VRB|\d{3})(\d{2,3})(G(\d{2,3}))?(KT|MPS|KMH)$/))) {
      out.wind = {
        code: t,
        direction: m[1],
        speed: +m[2],
        gust: m[4] ? +m[4] : null,
        unit: m[5],
      };
      continue;
    }
    if ((m = t.match(/^(\d{3})V(\d{3})$/))) {
      out.variableWind = { code: t, from: +m[1], to: +m[2] };
      continue;
    }
    const vis = parseVisibility(tokens, i);
    if (vis) {
      out.visibility = vis.data;
      i += vis.used - 1;
      continue;
    }
    if ((m = t.match(/^(FEW|SCT|BKN|OVC|VV)(\d{3}|\/\/\/)(CB|TCU)?$/))) {
      out.clouds.push({
        code: t,
        amount: m[1],
        feet: m[2] === "///" ? null : +m[2] * 100,
        type: m[3] || null,
      });
      continue;
    }
    if (/^(SKC|CLR|NSC|NCD)$/.test(t)) {
      out.clouds.push({ code: t, amount: t, feet: null, type: null });
      continue;
    }
    if ((m = t.match(/^(M?\d{2}|\/\/)\/(M?\d{2}|\/\/)$/))) {
      out.temp = tempValue(m[1]);
      out.dew = tempValue(m[2]);
      out.tempCode = t;
      continue;
    }
    if ((m = t.match(/^A(\d{4})$/))) {
      out.altimeter = {
        code: t,
        inhg: +m[1] / 100,
        hpa: Math.round((+m[1] / 100) * 33.8639),
      };
      continue;
    }
    if ((m = t.match(/^Q(\d{4})$/))) {
      out.altimeter = {
        code: t,
        hpa: +m[1],
        inhg: (+m[1] / 33.8639).toFixed(2),
      };
      continue;
    }
    if (/^[-+]?([A-Z]{2}){1,4}$/.test(t) || /^VC([A-Z]{2})+$/.test(t)) {
      const wx = decodeWeather(t);
      if (wx.description !== "Unrecognized weather group") out.weather.push(wx);
    }
  }
  return out;
}

function remarkTemp(sign, digits) {
  return (sign === "1" ? -1 : 1) * (Number(digits) / 10);
}
function remarkTimeText(v) {
  if (!v) return "";
  return v.length === 2
    ? `${v} minutes past the hour`
    : `${v.slice(0, 2)}:${v.slice(2)} UTC`;
}
function precipName(code) {
  const names = {
    RA: "Rain",
    DZ: "Drizzle",
    SN: "Snow",
    SG: "Snow grains",
    PL: "Ice pellets",
    GR: "Hail",
    GS: "Small hail/snow pellets",
    UP: "Unknown precipitation",
    FZRA: "Freezing rain",
    FZDZ: "Freezing drizzle",
    SHRA: "Rain showers",
    SHSN: "Snow showers",
  };
  return names[code] || code;
}
function decodePrecipTiming(t) {
  const m = t.match(/^([A-Z]{2,4})(?:B(\d{2}|\d{4}))?(?:E(\d{2}|\d{4}))?$/);
  if (!m || (!m[2] && !m[3])) return null;
  const valid = [
    "RA",
    "DZ",
    "SN",
    "SG",
    "PL",
    "GR",
    "GS",
    "UP",
    "FZRA",
    "FZDZ",
    "SHRA",
    "SHSN",
    "TS",
  ];
  if (!valid.includes(m[1])) return null;
  const name = m[1] === "TS" ? "Thunderstorm" : precipName(m[1]);
  const parts = [];
  if (m[2]) parts.push(`began at ${remarkTimeText(m[2])}`);
  if (m[3]) parts.push(`ended at ${remarkTimeText(m[3])}`);
  return `${name} ${parts.join(" and ")}`;
}
function pressureTendencyText(a) {
  return (
    {
      0: "increasing, then decreasing; same or higher than 3 hours ago",
      1: "increasing, then steady; higher than 3 hours ago",
      2: "increasing steadily or unsteadily",
      3: "decreasing or steady, then increasing; higher than 3 hours ago",
      4: "steady",
      5: "decreasing, then increasing; same or lower than 3 hours ago",
      6: "decreasing, then steady; lower than 3 hours ago",
      7: "decreasing steadily or unsteadily",
      8: "steady or increasing, then decreasing; lower than 3 hours ago",
    }[a] || "tendency code unavailable"
  );
}
function decodeRemarkToken(t, d) {
  let m, text;

  if (t === "AO1")
    return "Automated station without a precipitation discriminator";

  if (t === "AO2")
    return "Automated station with a precipitation discriminator";

  if (t === "$")
    return "Automated station maintenance/check indicator";

  if (/^TS(?:[BE]\d{2,4})+$/.test(t)) {
    const events = [...t.slice(2).matchAll(/([BE])(\d{2}|\d{4})/g)];

    return events
      .map((event) => {
        const action =
          event[1] === "B"
            ? "Thunderstorm began"
            : "Thunderstorm ended";

        return `${action} at ${remarkTimeText(event[2])}`;
      })
      .join("; ");
  }

  if (/^LTG(?:IC|CC|CG|CA)+$/.test(t)) {
    const codes = t.slice(3);
    const types = [];

    for (let i = 0; i < codes.length; i += 2) {
      const type = codes.slice(i, i + 2);

      if (type === "IC")
        types.push("in-cloud");
      else if (type === "CC")
        types.push("cloud-to-cloud");
      else if (type === "CG")
        types.push("cloud-to-ground");
      else if (type === "CA")
        types.push("cloud-to-air");
    }

    return types.length
      ? `${types.join(" and ")} lightning`
      : "Lightning";
  }

  const sensor = {
    PWINO: "Precipitation identifier information not available",
    PNO: "Precipitation amount not available",
    FZRANO: "Freezing-rain sensor information not available",
    TSNO: "Thunderstorm information not available",
    RVRNO: "Runway visual range information not available",
    SLPNO: "Sea-level pressure not available",
  };

  if (sensor[t])
    return sensor[t];

  if (t === "PRESRR")
    return "Pressure rising rapidly";

  if (t === "PRESFR")
    return "Pressure falling rapidly";

  if (t === "OCNL")
    return "Occasional";

  if (t === "FRQ")
    return "Frequent";

  if (t === "CONS")
    return "Continuous";

  if (t === "OHD")
    return "Overhead";

  if (t === "MOV")
    return "Moving";

  if (t === "TS")
    return "Thunderstorm";

  if (/^(N|NE|E|SE|S|SW|W|NW)$/.test(t)) {
    const directions = {
      N: "North",
      NE: "Northeast",
      E: "East",
      SE: "Southeast",
      S: "South",
      SW: "Southwest",
      W: "West",
      NW: "Northwest",
    };

    return directions[t];
  }

  if ((text = decodePrecipTiming(t)))
    return text;

  if ((m = t.match(/^SLP(\d{3})$/))) {
    let h = Number(m[1]) / 10;
    h += h < 50 ? 1000 : 900;

    return `Sea-level pressure ${h.toFixed(1)} hPa`;
  }

  if ((m = t.match(/^P(\d{4})$/))) {
    const n = Number(m[1]);

    return n === 0
      ? "Trace precipitation since the previous hourly observation (<0.01 in)"
      : `Hourly precipitation ${(n / 100).toFixed(2)} in since the previous hourly observation`;
  }

  if ((m = t.match(/^6(\d{4})$/))) {
    const n = Number(m[1]);

    return n === 0
      ? "Trace precipitation during the applicable 3- or 6-hour period (<0.01 in)"
      : `${(n / 100).toFixed(2)} in precipitation during the applicable 3- or 6-hour period`;
  }

  if ((m = t.match(/^7(\d{4})$/))) {
    const n = Number(m[1]);

    return n === 0
      ? "Trace precipitation during the past 24 hours (<0.01 in)"
      : `${(n / 100).toFixed(2)} in precipitation during the past 24 hours`;
  }

  if ((m = t.match(/^T([01])(\d{3})([01])(\d{3})$/))) {
    d.preciseTemp = remarkTemp(m[1], m[2]);
    d.preciseDew = remarkTemp(m[3], m[4]);

    return `Precise temperature ${d.preciseTemp.toFixed(1)}°C; dew point ${d.preciseDew.toFixed(1)}°C`;
  }
  if ((m = t.match(/^1([01])(\d{3})$/)))
    return `6-hour maximum temperature ${remarkTemp(m[1], m[2]).toFixed(1)}°C`;

  if ((m = t.match(/^2([01])(\d{3})$/)))
    return `6-hour minimum temperature ${remarkTemp(m[1], m[2]).toFixed(1)}°C`;

  if ((m = t.match(/^4([01])(\d{3})([01])(\d{3})$/)))
    return `24-hour maximum temperature ${remarkTemp(m[1], m[2]).toFixed(1)}°C; minimum ${remarkTemp(m[3], m[4]).toFixed(1)}°C`;

  if ((m = t.match(/^5([0-8])(\d{3})$/)))
    return `3-hour pressure tendency: ${pressureTendencyText(m[1])}; change ${(Number(m[2]) / 10).toFixed(1)} hPa`;

  if ((m = t.match(/^CIG(\d{3})V(\d{3})$/)))
    return `Ceiling varying between ${Number(m[1]) * 100} and ${Number(m[2]) * 100} ft`;

  return null;
}
// function decodeRemarkToken(t, d) {
//   let m, text;
//   if (t === "AO1")
//     return "Automated station without a precipitation discriminator";
//   if (t === "AO2")
//     return "Automated station with a precipitation discriminator";
//   if (t === "$") return "Automated station maintenance/check indicator";
//   const sensor = {
//     PWINO: "Precipitation identifier information not available",
//     PNO: "Precipitation amount not available",
//     FZRANO: "Freezing-rain sensor information not available",
//     TSNO: "Thunderstorm information not available",
//     RVRNO: "Runway visual range information not available",
//     SLPNO: "Sea-level pressure not available",
//   };
//   if (sensor[t]) return sensor[t];
//   if (t === "PRESRR") return "Pressure rising rapidly";
//   if (t === "PRESFR") return "Pressure falling rapidly";
//   if (t === "OCNL") return "Occasional";
//   if (t === "FRQ") return "Frequent";
//   if (t === "CONS") return "Continuous";

//   if (t === "OHD") return "Overhead";

//   if (t === "MOV") return "Moving";

//   if (t === "TS") return "Thunderstorm";

//   if (/^(N|NE|E|SE|S|SW|W|NW)$/.test(t)) {
//     const directions = {
//       N: "North",
//       NE: "Northeast",
//       E: "East",
//       SE: "Southeast",
//       S: "South",
//       SW: "Southwest",
//       W: "West",
//       NW: "Northwest",
//     };

//     return directions[t];
//   }
//   if ((text = decodePrecipTiming(t))) return text;
//   if ((m = t.match(/^SLP(\d{3})$/))) {
//     let h = Number(m[1]) / 10;
//     h += h < 50 ? 1000 : 900;
//     return `Sea-level pressure ${h.toFixed(1)} hPa`;
//   }
//   if ((m = t.match(/^P(\d{4})$/))) {
//     const n = Number(m[1]);
//     return n === 0
//       ? "Trace precipitation since the previous hourly observation (<0.01 in)"
//       : `Hourly precipitation ${(n / 100).toFixed(2)} in since the previous hourly observation`;
//   }
//   if ((m = t.match(/^6(\d{4})$/))) {
//     const n = Number(m[1]);
//     return n === 0
//       ? "Trace precipitation during the applicable 3- or 6-hour period (<0.01 in)"
//       : `${(n / 100).toFixed(2)} in precipitation during the applicable 3- or 6-hour period`;
//   }
//   if ((m = t.match(/^7(\d{4})$/))) {
//     const n = Number(m[1]);
//     return n === 0
//       ? "Trace precipitation during the past 24 hours (<0.01 in)"
//       : `${(n / 100).toFixed(2)} in precipitation during the past 24 hours`;
//   }
//   if ((m = t.match(/^T([01])(\d{3})([01])(\d{3})$/))) {
//     d.preciseTemp = remarkTemp(m[1], m[2]);
//     d.preciseDew = remarkTemp(m[3], m[4]);
//     return `Precise temperature ${d.preciseTemp.toFixed(1)}°C; dew point ${d.preciseDew.toFixed(1)}°C`;
//   }
//   if ((m = t.match(/^1([01])(\d{3})$/)))
//     return `6-hour maximum temperature ${remarkTemp(m[1], m[2]).toFixed(1)}°C`;
//   if ((m = t.match(/^2([01])(\d{3})$/)))
//     return `6-hour minimum temperature ${remarkTemp(m[1], m[2]).toFixed(1)}°C`;
//   if ((m = t.match(/^4([01])(\d{3})([01])(\d{3})$/)))
//     return `24-hour maximum temperature ${remarkTemp(m[1], m[2]).toFixed(1)}°C; minimum ${remarkTemp(m[3], m[4]).toFixed(1)}°C`;
//   if ((m = t.match(/^5([0-8])(\d{3})$/)))
//     return `3-hour pressure tendency: ${pressureTendencyText(m[1])}; change ${(Number(m[2]) / 10).toFixed(1)} hPa`;
//   if ((m = t.match(/^CIG(\d{3})V(\d{3})$/)))
//     return `Ceiling varying between ${Number(m[1]) * 100} and ${Number(m[2]) * 100} ft`;
//   return null;
// }
function parseRemarks(d) {
  if (!d.remarks) return;
  const rt = d.remarks.split(/\s+/);
  d.undecodedRemarks = [];
  for (let i = 0; i < rt.length; i++) {
    const t = rt[i];
    let m,
      text = null,
      code = t;
    if (
      t === "PK" &&
      rt[i + 1] === "WND" &&
      (m = (rt[i + 2] || "").match(/^(\d{3})(\d{2,3})\/(\d{2}|\d{4})$/))
    ) {
      code = `PK WND ${rt[i + 2]}`;
      text = `Peak wind from ${m[1]}° at ${Number(m[2])} knots at ${remarkTimeText(m[3])}`;
      i += 2;
    } else if (
      t === "WSHFT" &&
      (m = (rt[i + 1] || "").match(/^(\d{2}|\d{4})$/))
    ) {
      code = `WSHFT ${rt[i + 1]}`;
      text = `Wind shift began at ${remarkTimeText(m[1])}`;
      i++;
      if (rt[i + 1] === "FROPA") {
        code += " FROPA";
        text += " due to frontal passage";
        i++;
      }
    } else if (
      (t === "TWR" || t === "SFC") &&
      rt[i + 1] === "VIS" &&
      rt[i + 2]
    ) {
      code = `${t} VIS ${rt[i + 2]}`;
      text = `${t === "TWR" ? "Tower" : "Surface"} visibility ${rt[i + 2]} statute mile(s)`;
      i += 2;
    } else if (t === "VISNO") {
      const loc =
        rt[i + 1] && !decodeRemarkToken(rt[i + 1], d) ? rt[i + 1] : null;
      code = loc ? `VISNO ${loc}` : t;
      text = `Visibility sensor information not available${loc ? ` at ${loc}` : ""}`;
      if (loc) i++;
    } else if (t === "CHINO") {
      const loc =
        rt[i + 1] && !decodeRemarkToken(rt[i + 1], d) ? rt[i + 1] : null;
      code = loc ? `CHINO ${loc}` : t;
      text = `Cloud-height indicator information not available${loc ? ` at ${loc}` : ""}`;
      if (loc) i++;
    } else if (t === "VIRGA") {
      const dir =
        rt[i + 1] && /^(N|NE|E|SE|S|SW|W|NW|ALQDS)$/.test(rt[i + 1])
          ? rt[i + 1]
          : null;
      code = dir ? `VIRGA ${dir}` : t;
      text = `Virga${dir ? ` ${dir} of the station` : ""}`;
      if (dir) i++;

      // Thunderstorm beginning/ending times:
      // TSB31, TSE28, TSB31E47, TSE28B31, TSE28B31E47, etc.
    } else if ((m = t.match(/^TS((?:B|E)\d{2,4})+$/))) {
      const events = [...t.slice(2).matchAll(/([BE])(\d{2}|\d{4})/g)];

      code = t;

      text = events
        .map((event) => {
          const action =
            event[1] === "B" ? "Thunderstorm began" : "Thunderstorm ended";

          return `${action} at ${remarkTimeText(event[2])}`;
        })
        .join("; ");

      // Lightning frequency/type/location:
      // e.g. OCNL LTGICCG OHD
    } else if (
      /^(OCNL|FRQ|CONS)$/.test(t) &&
      /^LTG[A-Z]+$/.test(rt[i + 1] || "")
    ) {
      const frequency = {
        OCNL: "Occasional",
        FRQ: "Frequent",
        CONS: "Continuous",
      }[t];

      const lightningToken = rt[i + 1];
      const lightningCodes = lightningToken.slice(3);

      const types = [];
      if (lightningCodes.includes("IC")) types.push("in-cloud");
      if (lightningCodes.includes("CC")) types.push("cloud-to-cloud");
      if (lightningCodes.includes("CG")) types.push("cloud-to-ground");
      if (lightningCodes.includes("CA")) types.push("cloud-to-air");

      code = `${t} ${lightningToken}`;
      text = `${frequency} ${types.join(" and ")} lightning`;

      i++;

      if (rt[i + 1] === "OHD") {
        code += " OHD";
        text += " overhead";
        i++;
      }
    } else if (t === "TS") {
      const parts = ["TS"];
      let location = "";
      let movement = "";

      if (rt[i + 1] === "OHD") {
        parts.push("OHD");
        location = " overhead";
        i++;
      }

      if (
        rt[i + 1] === "MOV" &&
        /^(N|NE|E|SE|S|SW|W|NW)$/.test(rt[i + 2] || "")
      ) {
        parts.push("MOV", rt[i + 2]);
        movement = `, moving ${rt[i + 2]}`;
        i += 2;
      }

      code = parts.join(" ");
      text = `Thunderstorm${location}${movement}`;
    } else text = decodeRemarkToken(t, d);

    if (text) d.decodedRemarks.push({ code, text });
    else d.undecodedRemarks.push(t);
  }
  if (d.undecodedRemarks.length)
    d.decodedRemarks.push({
      code: d.undecodedRemarks.join(" "),
      text: "Additional remark(s) not yet decoded by this app",
    });
}
function displayTemp(d, key) {
  const v =
    key === "temp" ? (d.preciseTemp ?? d.temp) : (d.preciseDew ?? d.dew);
  return v;
}
function skyTrend(d) {
  if (!d.clouds.length) return { code: "—", description: "" };
  const code = d.clouds.map((c) => c.code).join(" · ");
  const description = d.clouds
    .map((c) => {
      if (c.amount === "CLR") return "Clear";
      if (c.amount === "SKC") return "Sky clear";
      if (c.amount === "NSC") return "No significant cloud";
      if (c.amount === "NCD") return "No cloud detected";
      const label = CLOUD[c.amount] || c.amount;
      const height = c.feet !== null ? ` at ${c.feet.toLocaleString()} ft` : "";
      const type =
        c.type === "CB"
          ? " cumulonimbus"
          : c.type === "TCU"
            ? " towering cumulus"
            : "";
      return `${label}${height}${type}`;
    })
    .join(" · ");
  return { code, description };
}
function trendArrow(curr, prev, decimals = 1) {
  if (curr == null || prev == null) return "";
  const diff = curr - prev;
  if (Math.abs(diff) < Math.pow(10, -decimals) / 2) return "→";
  return diff > 0
    ? `↑ +${diff.toFixed(decimals)}`
    : `↓ ${diff.toFixed(decimals)}`;
}
function renderTrend(ds) {
  const sec = $("#trendSection");
  if (ds.length < 2) {
    sec.hidden = true;
    return;
  }
  sec.hidden = false;
  const same = ds.every((d) => d.station === ds[0].station);
  $("#trendMeta").textContent =
    `${ds.length} observations${same ? ` · ${ds[0].station}` : ""} · oldest to newest`;
  const cell = (main, sub = "", delta = "") =>
    `<td><span class="trend-value">${main}${delta ? ` <span class="trend-delta">${delta}</span>` : ""}</span>${sub ? `<span class="trend-sub">${sub}</span>` : ""}</td>`;
  let h =
    "<thead><tr><th>OBSERVATION</th>" +
    ds
      .map(
        (d) =>
          `<th>${d.time ? `${String(d.time.hour).padStart(2, "0")}:${String(d.time.minute).padStart(2, "0")}Z` : "—"}<span class="trend-sub">${d.station}</span></th>`,
      )
      .join("") +
    "</tr></thead><tbody>";
  const rows = [];
  rows.push([
    "WIND",
    ds.map((d) => {
      if (!d.wind) return cell("—");
      const dir = d.wind.direction === "VRB" ? "VRB" : `${d.wind.direction}°`;
      const arrow = windArrowHTML(d.wind.direction);
      return `<td><div class="wind-cell">${arrow}<span><span class="trend-value">${dir} · ${d.wind.speed} kt${d.wind.gust ? ` G${d.wind.gust}` : ""}</span><span class="trend-sub">${d.wind.direction === "VRB" ? "Variable direction" : `FROM ${compass(+d.wind.direction)}`}</span></span></div></td>`;
    }),
  ]);
  rows.push(["VISIBILITY", ds.map((d) => cell(d.visibility?.display || "—"))]);
  rows.push([
    "SKY",
    ds.map((d) => {
      const sky = skyTrend(d);
      return cell(sky.code, sky.description);
    }),
  ]);
  rows.push([
    "TEMPERATURE",
    ds.map((d, i) => {
      let v = displayTemp(d, "temp"),
        pv = i ? displayTemp(ds[i - 1], "temp") : null;
      return cell(
        v == null ? "—" : `${v.toFixed(1)}°C`,
        v == null ? "" : `${cToF(v)}°F`,
        i && v != null ? trendArrow(v, pv, 1) : "",
      );
    }),
  ]);
  rows.push([
    "DEW POINT",
    ds.map((d, i) => {
      let v = displayTemp(d, "dew"),
        pv = i ? displayTemp(ds[i - 1], "dew") : null;
      return cell(
        v == null ? "—" : `${v.toFixed(1)}°C`,
        v == null ? "" : `${cToF(v)}°F`,
        i && v != null ? trendArrow(v, pv, 1) : "",
      );
    }),
  ]);
  rows.push([
    "ALTIMETER",
    ds.map((d, i) => {
      let v = d.altimeter ? Number(d.altimeter.inhg) : null,
        pv = i && ds[i - 1].altimeter ? Number(ds[i - 1].altimeter.inhg) : null;
      return cell(
        v == null ? "—" : `${v.toFixed(2)} inHg`,
        d.altimeter ? `${d.altimeter.hpa} hPa` : "",
        i && v != null ? trendArrow(v, pv, 2) : "",
      );
    }),
  ]);
  rows.push([
    "CATEGORY",
    ds.map((d) => {
      let c = flightCategory(d);
      return `<td>${c ? `<span class="category-pill">${c.name}</span>` : "—"}</td>`;
    }),
  ]);
  h +=
    rows
      .map(([name, cells]) => `<tr><th>${name}</th>${cells.join("")}</tr>`)
      .join("") + "</tbody>";
  $("#trendTable").innerHTML = h;
}
function parseMany(raw) {
  const lines = raw
    .split(/\r?\n/)
    .map((x) => x.trim())
    .filter(Boolean);
  if (!lines.length) throw new Error("Enter a METAR to decode.");
  return lines.map(parse).sort((a, b) => {
    if (!a.time || !b.time) return 0;
    return (
      a.time.day * 1440 +
      a.time.hour * 60 +
      a.time.minute -
      (b.time.day * 1440 + b.time.hour * 60 + b.time.minute)
    );
  });
}

function flightCategory(d) {
  let ceiling = null;
  d.clouds
    .filter((c) => ["BKN", "OVC", "VV"].includes(c.amount) && c.feet !== null)
    .forEach((c) => {
      if (ceiling === null || c.feet < ceiling) ceiling = c.feet;
    });
  const vis = d.visibility?.miles;
  let rank = 0,
    reason = []; // 0 VFR, 1 MVFR, 2 IFR, 3 LIFR
  if (ceiling !== null) {
    if (ceiling < 500) {
      rank = Math.max(rank, 3);
      reason.push(`ceiling ${ceiling} ft`);
    } else if (ceiling < 1000) {
      rank = Math.max(rank, 2);
      reason.push(`ceiling ${ceiling} ft`);
    } else if (ceiling <= 3000) {
      rank = Math.max(rank, 1);
      reason.push(`ceiling ${ceiling} ft`);
    }
  }
  if (vis !== null && vis !== undefined) {
    if (vis < 1) {
      rank = Math.max(rank, 3);
      reason.push(`visibility ${vis} SM`);
    } else if (vis < 3) {
      rank = Math.max(rank, 2);
      reason.push(`visibility ${vis} SM`);
    } else if (vis <= 5) {
      rank = Math.max(rank, 1);
      reason.push(`visibility ${vis} SM`);
    }
  }
  if (ceiling === null && (vis === null || vis === undefined)) return null;
  return {
    name: ["VFR", "MVFR", "IFR", "LIFR"][rank],
    reason: reason.length ? reason.join(" · ") : "ceiling and visibility",
  };
}

function tokenInfo(token, inRemarks = false) {
  let m;
  if (token === "METAR")
    return { title: "Report Type", meaning: "Routine aviation weather report" };
  if (token === "SPECI")
    return { title: "Report Type", meaning: "Special aviation weather report" };
  if (token === "AUTO")
    return { title: "Report Modifier", meaning: "Fully automated observation" };
  if (token === "COR")
    return { title: "Report Modifier", meaning: "Corrected report" };
  if (token === "RMK")
    return { title: "Remarks", meaning: "Remarks section begins" };
  if (/^[A-Z0-9]{4}$/.test(token) && !inRemarks)
    return { title: "Station", meaning: `Reporting station: ${token}` };
  if ((m = token.match(/^(\d{2})(\d{2})(\d{2})Z$/)))
    return {
      title: "Observation Time",
      meaning: `Observed on day ${+m[1]} at ${m[2]}:${m[3]} UTC`,
    };
  if ((m = token.match(/^(VRB|\d{3})(\d{2,3})(G(\d{2,3}))?(KT|MPS|KMH)$/))) {
    const dir =
      m[1] === "VRB"
        ? "variable direction"
        : `from ${m[1]}° (${compass(+m[1])})`;
    return {
      title: "Wind",
      meaning: `Wind ${dir} at ${+m[2]} ${m[5] === "KT" ? "knots" : m[5]}${m[4] ? `, gusting ${+m[4]}` : ""}`,
    };
  }
  if ((m = token.match(/^(\d{3})V(\d{3})$/)))
    return {
      title: "Wind — Variable Direction",
      meaning: `Wind direction varying between ${m[1]}° and ${m[2]}°`,
    };
  if (token === "CAVOK")
    return {
      title: "Visibility / Sky",
      meaning:
        "Visibility 10 km or more, no significant weather, and no significant cloud below CAVOK limits",
    };
  if (/^(M|P)?(?:\d+)?(?:\d\/\d)?SM$/.test(token))
    return {
      title: "Visibility",
      meaning: `Prevailing visibility: ${token.replace("SM", "")} statute mile(s)`,
    };
  if (/^\d{4}$/.test(token) && !inRemarks)
    return {
      title: "Visibility",
      meaning: `Prevailing visibility: ${Number(token) / 1000} km`,
    };
  if ((m = token.match(/^(FEW|SCT|BKN|OVC|VV)(\d{3}|\/\/\/)(CB|TCU)?$/))) {
    const feet =
      m[2] === "///" ? "height unavailable" : `${+m[2] * 100} ft AGL`;
    return {
      title: "Clouds",
      meaning: `${CLOUD[m[1]] || m[1]} at ${feet}${m[3] === "CB" ? " · cumulonimbus" : m[3] === "TCU" ? " · towering cumulus" : ""}`,
    };
  }
  if (CLOUD[token]) return { title: "Clouds", meaning: CLOUD[token] };
  if ((m = token.match(/^(M?\d{2}|\/\/)\/(M?\d{2}|\/\/)$/))) {
    const t = tempValue(m[1]),
      d = tempValue(m[2]);
    return {
      title: "Temperature / Dew Point",
      meaning: `Temperature ${t == null ? "unavailable" : t + "°C"}; dew point ${d == null ? "unavailable" : d + "°C"}`,
    };
  }
  if ((m = token.match(/^A(\d{4})$/)))
    return {
      title: "Altimeter",
      meaning: `Altimeter setting ${(Number(m[1]) / 100).toFixed(2)} inHg`,
    };
  if ((m = token.match(/^Q(\d{4})$/)))
    return { title: "Altimeter", meaning: `Altimeter setting ${+m[1]} hPa` };
  if (token === "AO1")
    return {
      title: "Remarks — Station Type",
      meaning: "Automated station without a precipitation discriminator",
    };
  if (token === "AO2")
    return {
      title: "Remarks — Station Type",
      meaning: "Automated station with a precipitation discriminator",
    };
  if (token === "PWINO")
    return {
      title: "Remarks — Sensor Status",
      meaning: "Precipitation identifier sensor not operating",
    };
  if ((m = token.match(/^T([01])(\d{3})([01])(\d{3})$/))) {
    const sg = (a, n) => (a === "1" ? -1 : 1) * (+n / 10);
    return {
      title: "Remarks — Precise Temperature",
      meaning: `Precise temperature ${sg(m[1], m[2]).toFixed(1)}°C; dew point ${sg(m[3], m[4]).toFixed(1)}°C`,
    };
  }
  if ((m = token.match(/^SLP(\d{3})$/))) {
    let h = +m[1] / 10;
    h += h < 50 ? 1000 : 900;
    return {
      title: "Remarks — Sea-Level Pressure",
      meaning: `Sea-level pressure ${h.toFixed(1)} hPa`,
    };
  }
  if (inRemarks) {
    const dummy = { preciseTemp: null, preciseDew: null };
    const decoded = decodeRemarkToken(token, dummy);
    if (decoded) return { title: "Remarks", meaning: decoded };
  }
  if (/^[-+]?([A-Z]{2}){1,4}$/.test(token) || /^VC([A-Z]{2})+$/.test(token)) {
    const wx = decodeWeather(token);
    if (!wx.description.includes("Unrecognized"))
      return { title: "Present Weather", meaning: wx.description };
  }
  return {
    title: inRemarks ? "Remarks" : "METAR Group",
    meaning: inRemarks
      ? "Remark code not yet decoded by this app"
      : "METAR group not yet decoded by this app",
  };
}
function interactiveRaw(ds) {
  return ds
    .map((d, reportIndex) => {
      let inRemarks = false;
      const parts = d.raw
        .split(/\s+/)
        .map((token, i) => {
          const info = tokenInfo(token, inRemarks);
          const html = `<span class="metar-token" tabindex="0" data-title="${escapeHtml(info.title)}" data-meaning="${escapeHtml(info.meaning)}" aria-label="${escapeHtml(info.title + ": " + token + ". " + info.meaning)}">${escapeHtml(token)}</span>`;
          if (token === "RMK") inRemarks = true;
          return html;
        })
        .join(" ");
      return `<span class="raw-report" data-report="${reportIndex + 1}">${parts}</span>`;
    })
    .join("\n");
}
function escapeHtml(s) {
  return String(s).replace(
    /[&<>\"]/g,
    (c) => ({ "&": "&amp;", "<": "&lt;", ">": "&gt;", '"': "&quot;" })[c],
  );
}
function bindRawTooltips() {
  const tip = $("#metarTooltip");
  if (!tip) return;
  const show = (e) => {
    const el = e.currentTarget;
    tip.innerHTML = `<strong>${escapeHtml(el.dataset.title)}</strong><code class="tooltip-code">${escapeHtml(el.textContent)}</code><span>${el.dataset.meaning}</span>`;
    tip.hidden = false;
  };
  document.querySelectorAll(".metar-token").forEach((el) => {
    el.addEventListener("mouseenter", show);
    el.addEventListener("focus", show);
  });
}
function windArrowHTML(direction) {
  if (direction === "VRB")
    return `<span class="wind-arrow" tabindex="0" data-tooltip="Variable wind direction" aria-label="Variable wind direction">↻</span>`;
  const from = Number(direction),
    to = (from + 180) % 360;
  const fromText = String(from).padStart(3, "0"),
    toText = String(to).padStart(3, "0");
  return `<span class="wind-arrow" tabindex="0" style="--wind-dir:${from}deg" data-tooltip="Airflow: from ${fromText}° toward ${toText}°" aria-label="Airflow from ${fromText} degrees toward ${toText} degrees">→</span>`;
}
function card(label, value, sub, code, valueClass = "") {
  return `<article class="card"><span class="label">${label}</span><strong class="value ${valueClass}">${value}</strong>${sub ? `<span class="sub">${sub}</span>` : ""}${code ? `<code class="code">${code}</code>` : ""}</article>`;
}

function cloudCard(d) {
  const clearCodes = ["CLR", "SKC", "NSC", "NCD"];
  const clearCloud = d.clouds.find((c) => clearCodes.includes(c.amount));

  // Clear-sky reports
  if (clearCloud) {
    return `
      <article class="card cloud-card">
        <span class="label">CLOUDS / SKY</span>

        <div class="cloud-clear">
          <strong class="cloud-clear-value">
            ${CLOUD[clearCloud.amount] || clearCloud.amount}
          </strong>
        </div>

        <code class="code">${clearCloud.code}</code>
      </article>
    `;
  }

  // CAVOK with no separately reported cloud layers
  if (!d.clouds.length && d.visibility?.cavok) {
    return `
      <article class="card cloud-card">
        <span class="label">CLOUDS / SKY</span>

        <div class="cloud-clear">
          <strong class="cloud-clear-value">No significant cloud</strong>
          <span class="sub">CAVOK</span>
        </div>

        <code class="code">CAVOK</code>
      </article>
    `;
  }

  // No cloud information in the report
  if (!d.clouds.length) {
    return `
      <article class="card cloud-card">
        <span class="label">CLOUDS / SKY</span>

        <div class="cloud-clear">
          <strong class="cloud-clear-value">Not reported</strong>
        </div>
      </article>
    `;
  }

  // Determine the lowest ceiling-producing layer.
  const ceiling =
    [...d.clouds]
      .filter((c) => ["BKN", "OVC", "VV"].includes(c.amount) && c.feet !== null)
      .sort((a, b) => a.feet - b.feet)[0] || null;

  // Known-height layers are displayed highest to lowest.
  // Unknown-height layers are retained at the bottom.
  const layers = [...d.clouds].sort((a, b) => {
    if (a.feet === null && b.feet === null) return 0;
    if (a.feet === null) return 1;
    if (b.feet === null) return -1;
    return b.feet - a.feet;
  });

  const layerHTML = layers
    .map((c) => {
      const isCeiling = c === ceiling;

      let cloudType = "";

      if (c.type === "CB") {
        cloudType = " · CUMULONIMBUS";
      } else if (c.type === "TCU") {
        cloudType = " · TOWERING CUMULUS";
      }

      const height =
        c.feet !== null ? `${c.feet.toLocaleString()} FT` : "HEIGHT N/A";

      return `
        <div class="cloud-layer ${isCeiling ? "cloud-layer-ceiling" : ""}">
          <span class="cloud-height">${height}</span>



          <span class="cloud-rule ${isCeiling ? "cloud-rule-with-label" : ""}" aria-hidden="true">
            ${isCeiling ? `<span class="ceiling-tag">CEILING</span>` : ""}
          </span>

          <span class="cloud-layer-info">
            <strong>${c.amount}</strong>
            <span>${CLOUD[c.amount] || c.amount}${cloudType}</span>
          </span>
        </div>
      `;
    })
    .join("");

  const codes = d.clouds.map((c) => c.code).join(" ");

  return `
    <article class="card cloud-card">
      <span class="label">CLOUDS / SKY</span>

      <div class="cloud-layers">
        ${layerHTML}
      </div>

      <code class="code">${codes}</code>
    </article>
  `;
}

function capitalizeFirst(text) {
  if (!text) return "";
  return text.charAt(0).toUpperCase() + text.slice(1);
}

function render(d) {
  $("#station").textContent = d.station;
  $("#reportType").textContent = d.type;
  $("#rawOutput").textContent = d.raw;
  $("#stationDescription").textContent = stationDescription(d);
  $("#observationTime").textContent = stationLocalTime(d);
  const cat = flightCategory(d);
  $("#categoryBlock").hidden = !cat;
  if (cat) {
    $("#flightCategory").textContent = cat.name;
    $("#categoryReason").textContent = cat.reason;
  }
  let cards = [];
  if (d.wind) {
    const unit = d.wind.unit === "KT" ? "kt" : d.wind.unit.toLowerCase();
    const dir =
      d.wind.direction === "VRB" ? "Variable" : `${d.wind.direction}°`;
    const sub =
      (d.wind.direction === "VRB"
        ? "Variable direction"
        : // : compass(+d.wind.direction)) +
          `From ${compass(+d.wind.direction)}`) +
      (d.wind.gust ? ` · gusting ${d.wind.gust} ${unit}` : "") +
      (d.variableWind
        ? ` · varying ${d.variableWind.from}°–${d.variableWind.to}°`
        : "");
    cards.push(
      card(
        "WIND",
        `${windArrowHTML(d.wind.direction)}<span>${dir} · ${d.wind.speed} ${unit}</span>`,
        sub,
        d.wind.code,
        "wind-card-value",
      ),
    );
  }
  if (d.visibility)
    cards.push(
      card(
        "VISIBILITY",
        d.visibility.display,
        d.visibility.cavok ? "CAVOK" : "Prevailing visibility",
        d.visibility.code,
      ),
    );
  if (d.temp !== null)
    cards.push(
      card("TEMPERATURE", `${d.temp}°C`, `${cToF(d.temp)}°F`, d.tempCode),
    );
  if (d.dew !== null)
    cards.push(card("DEW POINT", `${d.dew}°C`, `${cToF(d.dew)}°F`, d.tempCode));
  if (d.altimeter)
    cards.push(
      card(
        "ALTIMETER",
        `${d.altimeter.inhg} inHg`,
        `${d.altimeter.hpa} hPa`,
        d.altimeter.code,
      ),
    );
  // const cloudValue = d.clouds.length
  //   ? d.clouds.map((c) => CLOUD[c.amount] || c.amount).join(" · ")
  //   : d.visibility?.cavok
  //     ? "No significant cloud"
  //     : "Not reported";
  // const cloudSub = d.clouds.length
  //   ? d.clouds
  //       .map((c) =>
  //         c.feet !== null
  //           ? `${c.feet.toLocaleString()} ft AGL${c.type ? ` ${c.type}` : ""}`
  //           : CLOUD[c.amount] || c.amount,
  //       )
  //       .join(" · ")
  //   : d.visibility?.cavok
  //     ? "CAVOK"
  //     : "No cloud group";
  // const cloudCode = d.clouds.length
  //   ? d.clouds.map((c) => c.code).join(" ")
  //   : d.visibility?.cavok
  //     ? "CAVOK"
  //     : "—";
  // cards.push(card("CLOUDS", cloudValue, cloudSub, cloudCode));
  cards.push(cloudCard(d));
  $("#cards").innerHTML = cards.join("");
  $("#weatherSection").hidden = !d.weather.length;
  $("#weatherList").innerHTML = d.weather
    .map(
      (w) =>
        `<div class="detail-row"><code>${w.code}</code><strong>${capitalizeFirst(w.description)}</strong><span>Present weather</span></div>`,
    )
    .join("");
  $("#remarksSection").hidden = !d.remarks;
  let old = $("#remarksSection .remarks-decoded");
  if (old) old.remove();
  if (d.decodedRemarks.length) {
    const box = document.createElement("div");
    box.className = "remarks-decoded";
    box.innerHTML = d.decodedRemarks
      .map(
        (r) =>
          `<div class="remark-item"><code>${r.code}</code><span>${r.text}</span></div>`,
      )
      .join("");
    $("#remarksSection").appendChild(box);
  }
  results.hidden = false;
  errorBox.hidden = true;
}
async function decode() {
  try {
    if (!stationDataReady) await stationDataPromise;
    const ds = parseMany(input.value);
    render(ds[ds.length - 1]);
    renderTrend(ds);
    $("#rawOutput").innerHTML = interactiveRaw(ds);
    bindRawTooltips();
  } catch (e) {
    errorBox.textContent = e.message;
    errorBox.hidden = false;
    results.hidden = true;
  }
}
$("#decodeBtn").addEventListener("click", decode);
$("#exampleBtn").addEventListener("click", () => {
  input.value =
    "METAR K57C 271815Z AUTO 33003KT 10SM CLR 21/10 A3013 RMK AO2 T02060102 PWINO\nMETAR K57C 271835Z AUTO 36003KT 10SM CLR 20/11 A3012 RMK AO2 T02010107 PWINO\nMETAR K57C 271855Z AUTO 05003KT 10SM CLR 21/10 A3011 RMK AO2 T02070099 PWINO";
  decode();
});
input.addEventListener("keydown", (e) => {
  if ((e.ctrlKey || e.metaKey) && e.key === "Enter") decode();
});
$("#copyBtn").addEventListener("click", async () => {
  await navigator.clipboard.writeText(input.value.trim());
  $("#copyBtn").textContent = "Copied";
  setTimeout(() => ($("#copyBtn").textContent = "Copy"), 1200);
});
